name: Ruby

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 Checkout  
      uses: actions/checkout@v3
   
    - name: Step 2 Instalar ruby 
      uses: ruby/setup-ruby@v1
       
      with:
        ruby-version: '3.0'
        bundler-cache: true # executa 'bundle install' e armazena em cache as gems instaladas

      
    - name: Step 3 Run test 
      run:
          bundle exec cucumber -p ci
          
    - name: Step 4 Archive production artifacts 
      uses: actions/upload-artifact@v3
      with: 
          name: reports
          path: ./reports/relatorio.html
