name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:



jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 Checkout code
   
    - name: Step 2 Set up Ruby 
      uses: ruby/setup-ruby@v1
       
      with:
        ruby-version: '3.0'
        bundler-cache: true 

      
    - name: Step 3 Execute test 
      run:
          bundle exec cucumber -p ci
          
    - name: Step 4 Archive production artifacts
      uses: actions/upload-artifact@v3
      with: 
          name: reports
          path: ./reports/relatorio.html
